[phases.setup]
nixPkgs = ["python311","python311Packages.pip","python311Packages.setuptools","python311Packages.wheel"]
aptPkgs = ["libgl1","libglib2.0-0","libgomp1","build-essential","ca-certificates"]

[phases.install]
# wheels-only + explicit wheels for the heavy ones first
cmds = [
  "python3 -m pip install -U pip wheel setuptools",
  "PIP_ONLY_BINARY=:all: pip3 install --only-binary=:all: numpy==1.26.4 pandas==2.2.2 pyarrow==16.1.0 Pillow==10.4.0",
  "pip3 install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn cabi_outfits.api:app --host 0.0.0.0 --port $PORT --app-dir src"
