# Railway Nixpacks plan (no Docker)
[phases.setup]
# Install Python + pip via Nix (fixes "No module named pip")
nixPkgs = ["python311","python311Packages.pip","python311Packages.setuptools","python311Packages.wheel"]
# Minimal system libs needed by torch/faiss/pillow on CPU
aptPkgs = ["libgl1","libglib2.0-0","libgomp1","build-essential","ca-certificates"]

[phases.install]
# Use python3/pip3 explicitly (works with Nix Python)
cmds = [
  "python3 -m pip install -U pip wheel setuptools",
  "pip3 install --index-url https://download.pytorch.org/whl/cpu torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2",
  "pip3 install --no-cache-dir faiss-cpu==1.7.4 pyarrow==16.1.0",
  "pip3 install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn cabi_outfits.api:app --host 0.0.0.0 --port $PORT --app-dir src"
